### ISSUE TITLE
New name for the "NotKilling" status

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#1041]
I've implemented the test view in #1014 , however I don't think the view is very clear with the "NotKilling" column there.

![](https://user-images.githubusercontent.com/1828233/115001820-50104200-9ea4-11eb-9010-26fff357587f.png)

(Note, feedback on UI etc plz in the PR and not here)

I would personally expect that `Killing` + `NotKilling` would result in `Total tests`. However, that's not the case because of `NotCovering` not being included in `NotKilling`. I think we should really find a better word for `NotKilling`.

I personally like `Pacifist` better. It sounds different enough from `Killing` and `NotCovering` to understand what's going on. I know that the word "Pacifist" isn't all that common, but I do think it is growing in popularity with the rise in popularity of "nerd culture". 

I'm open to other suggestions as well, but everytime I think about it I fall back to pacifist 🤷‍♂️

Note: no matter what we choose, we should include popover or useful links that explain what everything means.

**Comment by rouke-broersma** [comment]
Pacifists is not a status. A pacifist is a person that does not wish to use violence. To fit the theme `Killing` would have to become `Killers` and `Not Covering` would have to be `Deserters`.

**Comment by nicojs** [comment]
As you can see, I've dropped a message in the general mutation testing discord. Not a lot of responses with regards to naming yet.

I've been thinking about it a lot and maybe we need new names for all states to make it better. How about `productive`, `passive` and `blind`. A _productive test_ is a test that killed at least one mutant. A _passive test_ is a test that doesn't kill but covers a mutant. A _blind test_ doesn't cover a specific mutant (or is only there to "cover" a static mutant, but apparently isn't killing said mutant).

**Comment by rouke-broersma** [comment]
Perhaps we should have a call with all strykers to discuss this.

**Comment by nicojs** [comment]
So... you're not saying "no" yet? 😉

**Comment by PauloGoncalvesBH** [comment]
Hi guys, my suggestion is as follows:
Leave the names as they are, to look like the **Mutants** tab, which displays the words `killed`, `survived`, `not coverage`, so if in the **tests** tab we keep `killing`, `not killing` and `not coverage`, will facilitate the user's understanding of what it refers to.
But as we know that it is not very clear information and can confuse users, I suggest creating an information information button at the end of each word (in the **tests** and **mutants** tab), where when the user hovers, he goes display a short explanation of what it refers to.
Because I believe that, even if we find a better name option than `not killing`, users can still be in doubt as to what their names are and will go after the documentation.
Let's bring a piece of documentation to the report.

**Comment by nicojs** [comment]
Thanks for pitching in @PauloGoncalvesBH 💗I've opened #1060 for the tooltip. It's a separate issue, definitely a valid point.

Did you deliberately change `NotCovering` to `not coverage`? Maybe `no coverage` is better?

**Comment by PauloGoncalvesBH** [comment]
@nicojs I wrote it wrong, I hadn't noticed that I made this change.

**Comment by rouke-broersma** [comment]
NoCoverage would conflict with the Mutant statuses so that would be confusing imo

**Comment by nicojs** [comment]
I had a nice talk with @JSmits-utwente earlier and he suggested "Observing" instead of "Not Killing". Using this solves the problem with "Not Killing".

**Comment by nicojs** [comment]
@rouke-broersma, @hugo-vrijswijk, and I had a nice discussion. We've chosen to rename `NotKilling` to `Covering`. This doesn't fully resolve this issue (`covering + not covering ~= total`), but it is a bit nicer at least. 

We can later make things clearer by adding a visual division in the UI: like this.

![image](https://user-images.githubusercontent.com/1828233/116548204-2e777780-a8f4-11eb-8fc6-3e62dc01c775.png)
