### ISSUE TITLE
Suggestion: Display map structure similar to Github

### ISSUE THREAD

**Issue by Wmaarts** [stryker-mutator/mutation-testing-elements#11]
(moved from #2)
Preview:
![afbeelding](https://user-images.githubusercontent.com/5868064/53345149-8715e900-3914-11e9-839d-ae603db38f55.png)

(I think the image speaks for itself? 😁 )

Note that I included the path of root folder in header, similar to how it's currently displayed when opening a specific file.

**Comment by hugo-vrijswijk** [comment]
Shouldn't `core/src/main...` replace the `All files` bit? So, have the text when in root, and the subpath when in a subfolder?

**Comment by nicojs** [comment]
What happens when you click on a directory? Does it "fold open"? Or navigate to "a new page" (still is a single page app of course).

The problem with using the directory name instead of "All files" is that, for JavaScript projects, the directory name would most likely be "src" or something non-descriptive like that.

**Comment by hugo-vrijswijk** [comment]
Why would that be non-descriptive? I know the structure of my project, so I know where I am if it says 'src'

**Comment by Wmaarts** [comment]
> Shouldn't `core/src/main...` replace the `All files` bit?

I kept the All Files because in the 'detail-view' of a file it shows it exactly like this, but then the All Files is a link back to the main page. I thought it would be more consistent this way.

> Does it "fold open"? Or navigate to "a new page"

I would say new page as well, that's what Github does after all. Folding open could be cool tbh, although it might become unintuitive for folders with many files? 🤔

**Comment by nicojs** [comment]
I've implemented the directory structure view:

![image](https://user-images.githubusercontent.com/1828233/53472886-36fc6b00-3a69-11e9-84f1-e483d59c0682.png)

I'm still calling it "all files" for now. I think that, however you feel, it is not a show stopper.

I've released it under version `0.0.7`. Could you please try it out? You can close this issue if you're satisfied.

**Comment by hugo-vrijswijk** [comment]
Very cool! I've played around with it a bit and it seems to work very well with multiple directories. Feels like a very smooth experience. As far as I'm concerned this issue can be closed.
