### ISSUE TITLE
Navigation is slow

### ISSUE THREAD

**Issue by danny12321** [stryker-mutator/mutation-testing-elements#1478]
When viewing a large report de navigation between pages is slow. I found this when viewing a report of rxjs. It takes about 4 seconds to switch from page as could be seen below.

## Example
![slow_html_report](https://user-images.githubusercontent.com/15829978/139417361-6b1ba25c-2702-44c0-81be-7610a7f3f24b.gif)

**Comment by nicojs** [comment]
[Uploading index (2).zip…]()

Example report

**Comment by hugo-vrijswijk** [comment]
> Uploading index (2).zip…

I think something went wrong with your upload, it just links to this issue

**Comment by nicojs** [comment]
[example.zip](https://github.com/stryker-mutator/mutation-testing-elements/files/7674571/index.2.zip)

**Comment by nicojs** [comment]
I see a lot of very big `coveredBy` arrays. Any idea why that could be @danny12321 ? Normally `coveredBy` is a more modest amount.

**Comment by danny12321** [comment]
I'm running rxjs again because I don't know the exact settings I used. But I guess it has something to do with the 3210 tests that rxjs has. When the run is completed (~4 hours ⌛) I will share the settings I used.

**Comment by nicojs** [comment]
The json result would be great 😃

**Comment by danny12321** [comment]
The results are in!
[mutation.zip](https://github.com/stryker-mutator/mutation-testing-elements/files/7675895/mutation.zip)

stryker.conf.json
```json
{
  "$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  "packageManager": "npm",
  "reporters": [
    "html",
    "clear-text",
    "progress",
    "json"
  ],
  "testRunner": "mocha",
  "coverageAnalysis": "perTest",
  "checkers": [
    "typescript"
  ],
  "tsconfigFile": "tsconfig.json",
  "buildCommand": "npm run compile",
  "mochaOptions": {
    "spec": [
      "dist/spec/**/*-spec.js"
    ],
    "config": "spec/support/.mocharc.js"
  }
}
```
