### ISSUE TITLE
report color code should represent failure or pass

### ISSUE THREAD

**Issue by nagkumar** [stryker-mutator/mutation-testing-elements#1479]
When we expand failed Mutation.. that is shown in red..
![image](https://user-images.githubusercontent.com/332234/139420332-e27a9d3c-bcd3-4472-955f-c6655a679f24.png)

It should be the code that failed in red color

![image](https://user-images.githubusercontent.com/332234/139420397-39494ec9-1d9d-4c5d-b2ba-e624698c1e16.png)

**Comment by rouke-broersma** [comment]
@nagkumar the new report has been out for a while, does it solve your issue?
