### ISSUE TITLE
Where to host additional information like "mutatorName"

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#16]
Where do we want to host additional information about the mutators? Like MutatorName? This is now missing entirely from the report, but it might be useful. For example, you can disable certain mutators by name, just as soon as you know the mutator name.

In the old report, we had a popup using bootstrap js:

![image](https://user-images.githubusercontent.com/1828233/54669236-2d5aa600-4af1-11e9-8ed1-5148218220b4.png)

I don't want to load the entire bootstrap js (it isn't "webpackable" and relies on JQuery 😢 ). So I would need to recreate it. At the same time, I'm not really happy with putting this info in a popup.

We also had a table with all the info:

![image](https://user-images.githubusercontent.com/1828233/54669362-7ca0d680-4af1-11e9-9200-f5230071113b.png)

I wasn't happy with that either. It can feel like an overload of info. It also took valuable space at the right side of the screen, resulting in a horizontal scrollbar for the code area.

What solution do we want? 

We can do something like a drawer panel and fit the table in that. We could make it so that you can activate, or deactivate a mutant from there as well. https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sidenav

Other ideas?

**Comment by richardwerkman** [comment]
We could add a side panel where a 'selected' mutant is shown. The side panel could scroll with the page so it's always visible, even on large files.

**Comment by nicojs** [comment]
What is a "selected mutant"? You can expand multiple mutants in code, right? You can also expand all or collapse all with the button. Not sure if it would help the user of all those mutants are shown.

**Comment by richardwerkman** [comment]
A selected mutant is something different from an opened mutant. By clicking on a mutant you open it and you set it as 'selected mutant'. Then when you click a new mutant you open that one too and the selected mutant switches to the last clicked. That way there is always only 1 selected mutant.

We could also introduce a new colour to highlight the currently selected mutant?

**Comment by hugo-vrijswijk** [comment]
I feel like the table is a bit unnecessary. The amount of mutants, their locations, and replacements are already clear. The only thing that's not currently shown is the category and status. Perhaps we could have different colours per category (dynamically, as not every framework has the same categories).

@nicojs What was the reason you don't like the popup? To me it seems like an elegant solution

**Comment by nicojs** [comment]
@simondel thanks for tuning in.

The question isn't _how_, but _what_. In other words, how do we want to show this info? If we can come to a consensus here, I'll be happy to find for small/big libraries.

Popup, table, drawer, something else, you tell me.

For now, I'm leaning towards a simple popup myself.
