### ISSUE TITLE
Support Mull: the C(++) mutation testing framework

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#19]
[Mull](https://github.com/mull-project/mull) is interested in using mutation testing elements, see https://twitter.com/1101_debian/status/1113372029342842889

@AlexDenisov
I don't think we need to do any changes to the schema, do you agree? We would need to add `C` and `C++` to the highlight js imports.

**Comment by AlexDenisov** [comment]
I would need to get familiar with the JSON schema first, then I can give more precise answer.
I will get back to this issue next week, pretty busy before that.

**Comment by AlexDenisov** [comment]
jfyi, the work is being done, slowly, but surely ;)
https://github.com/mull-project/mull/pull/517
