### ISSUE TITLE
Mutation report elements 1.0.2 hover tooltip hidden when lower on page

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/mutation-testing-elements#23]
See:

![image](https://user-images.githubusercontent.com/3595932/55617825-40c66c00-5795-11e9-912f-cf1ed857b081.png)

**Comment by hugo-vrijswijk** [comment]
The same happens when a mutator is too far left on the page

**Comment by nicojs** [comment]
@Mobrockers didn't it add a scroll bar when that happens?

@hugo-vrijswijk that shouldn't happen, can you share a screenshot?

**Comment by hugo-vrijswijk** [comment]
@nicojs It is also fixed with #24
