### ISSUE TITLE
Add `Pending` status to mutation-testing-report-schema.json

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/mutation-testing-elements#2424]
# Motivation

To give some background information: I am currently doing my internship at the company behind Stryker. The goal of my internship is to make the mutation testing report realtime, because currently the user has to wait before the complete mutation testing proces is done to see any feedback in the report.

To make this possible, a new status type should be added to the `status` property in the `mutation-testing-report-schema.json`. This new status will be called `Pending`. `Pending` means that the mutant is generated, but not yet run.

The reason why this is needed, is because of the following idea:
1. Every Stryker tool already knows what mutants are generated. This can be used to display the "empty" mutation report. This empty mutation report will be called the "initial state".
2. In the "empty" report, every mutant will have the state `Pending`.
3. To make the report realtime, we supply updates to the report from a Stryker tool using Server Sent Events. The only thing that would be sent is the mutant `id` and the new `state` of said mutant.
   - The reason for using Server Sent Events, is because the protocol is simpler and the communication direction is unidirectional. This makes it perfect for this usecase.
4. Using these events, everything will be updated in realtime in the report which will make it faster to recieve feedback<sup>[1]</sup>

<sup>1</sup> Note that the actual testing process will not be faster, that is up to the tool. This should only be for getting the actual feedback faster on-the-go.

**Comment by psfinaki** [comment]
Sounds cool! Good luck :)
