### ISSUE TITLE
theme-changed CI browser tests failing on windows since some days

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/mutation-testing-elements#2495]
https://github.com/stryker-mutator/mutation-testing-elements/actions/runs/4882628041

**Comment by rouke-broersma** [comment]
`AssertionError: expected '#18181b' to equal ' #18181b'`
`AssertionError: expected '#fff' to equal ' #fff'`

??

**Comment by rouke-broersma** [comment]
Something must have changed in webpack because that's the only thing that's been changed since the tests succeeded.

**Comment by hugo-vrijswijk** [comment]
It could also be a different Windows or Chrome version 🙄

**Comment by rouke-broersma** [comment]
The issue indeed appears to be chrome versions..

Windows agents: 113.0.5672.64
Linux agents: Chrome Headless 112.0.5615.165
My local wsl: Chrome 113.0.0.0 (Linux x86_64)

Seems that the results are different from chrome 113, but the linux agents have not yet been updated.

@hugo-vrijswijk @nicojs how do we want to deal with this? Create OS specific tests until the linux agents have been updated? Ignore the tests until the linux agents have been updated?
