### ISSUE TITLE
File type icons

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/mutation-testing-elements#26]
It'd be cool to have file type specific icons, similar to VS Code. We could use something like [pretty-file-icons](https://www.npmjs.com/package/pretty-file-icons) for it. Mapping icons by hand is probably not a very good idea.

Note: `pretty-file-icons` seems to be specific for https://www.flaticon.com, which I am not a huge fan of

![image](https://user-images.githubusercontent.com/10114577/55628658-93ae1c80-57b1-11e9-88eb-6f1bfbbd291d.png)

**Comment by nicojs** [comment]
We should also keep download size in mind!

**Comment by hugo-vrijswijk** [comment]
Maybe we should add them by hand, then. Similar to highlight.js. If the files are svg it shouldn't impact download size too much

**Comment by nicojs** [comment]
I would only support languages that make sense. Rest should have the default file octocon
