### ISSUE TITLE
Progress bar colours don't match mutant status colour

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/mutation-testing-elements#2639]
![image](https://github.com/stryker-mutator/mutation-testing-elements/assets/3595932/f942a9ee-2b33-46c6-966e-5f1db2dc859b)

Red is survived + nocoverage, however the reporting colour for nocoverage is orange:

![image](https://github.com/stryker-mutator/mutation-testing-elements/assets/3595932/ebdd2f9b-945a-4d7a-8e5d-f014da9d4af5)

Orange is ignored + runtime error + compile error, however the reporting colour for these statuses is grey

![image](https://github.com/stryker-mutator/mutation-testing-elements/assets/3595932/878516b3-f9f1-44c1-b69f-137b4206093b)

https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/elements/src/components/result-status-bar/result-status-bar.ts#L117

**Comment by xandervedder** [comment]
Perhaps this was done because of the following comment:

https://github.com/stryker-mutator/mutation-testing-elements/pull/2560#issuecomment-1584273555

Otherwise the `ignored` or `compileerror` would blend in with `pending` which doesn't make it easy to see what mutants still need to be tested 🤔

**Comment by rouke-broersma** [comment]
Perhaps we should simply choose a new color for pending, since that status is new and unfamiliar anyway.

**Comment by nicojs** [comment]
I think we should only show _valid_ mutants here. So no ignored / error.

**Comment by xandervedder** [comment]
I'll pick this up today since it has been annoying me too 😄
