### ISSUE TITLE
Add line number support

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/mutation-testing-elements#30]
As requested through stryker-net [#458](https://github.com/stryker-mutator/stryker-net/issues/458) we should add line numbers to the file view. This makes finding the mutation in the original source code easier.

**Comment by nicojs** [comment]
That it does. Line numbers [are not supported by highlightjs by design](https://highlightjs.readthedocs.io/en/latest/line-numbers.html). So we'll have to see how easy it is to add.

**Comment by richardwerkman** [comment]
Could we use http://wcoder.github.io/highlightjs-line-numbers.js/? I've tried to include the package but it keeps saying `highlight.js not detected!`...

I'm not a typescript expert so I don't know if this has to do with the way I load the package or I made another mistake.

@nicojs could you take a look at the code? https://github.com/stryker-mutator/mutation-testing-elements/compare/line-numbers

**Comment by nicojs** [comment]
Highlightjs is packaged with webpack, instead of directly loaded in the page. That's why you get the error. I will have a look.

**Comment by hugo-vrijswijk** [comment]
An alternative would be to use [Prism](https://prismjs.com/) which [supports line numbers](https://prismjs.com/plugins/line-numbers/)
