### ISSUE TITLE
Literals look like killed mutants

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/mutation-testing-elements#31]
In a report generated by Stryker.NET, literal expressions look like killed mutations. This can be confusing. 

![image](https://user-images.githubusercontent.com/14224500/56046383-64fcec80-5d43-11e9-8254-54931fed130a.png)

As seen in this example the `null` and `true` are green, but also represent survived mutations. 

This probably has to do with the syntax highlighting and I'm not sure if we can influence this much?

**Comment by hugo-vrijswijk** [comment]
I don't think we can influence syntax highlighting much (or if we even want to get into that). An alternative could be  changing the theme. 

I ran into a similar thing where something in Stryker4s had red highlighting (even though it was killed), so this gets a 👍 from me

**Comment by nicojs** [comment]
What would you suggest the color to be? We might be able to override it with css. We could also try to choose a highlightjs theme that doens't have red, blue or yellow in it.

**Comment by richardwerkman** [comment]
In my VS bool literals are highlighted light blue. We could try to follow the VS colors? At least for csharp of course ;)

**Comment by hugo-vrijswijk** [comment]
It'd be cool to be able to set a property on the `mutation-testing-elements` component for a highlight.js theme. Like so: `<mutation-test-report-app highlight-theme="visualstudio"></mutation-test-report-app>`.

No idea if the highlight.js themes are already included in the build, and if we include them, how much that would influence the build size.

**Comment by nicojs** [comment]
> No idea if the highlight.js themes are already included in the build, and if we include them, how much that would influence the build size.

Right now, only one highlight.js style is included. We could include more, but that will impact the bundle size. Although highlight js themes are < 1kb, so not _that_ expensive.

>In my VS bool literals are highlighted light blue. We could try to follow the VS colors? At least for csharp of course ;)

Choosing different themes for different languages is a slippery slope. How about people that like a dark theme? Or Sublime Material? Or GreenShah? Even github doesn't make their theme configurable and for good reason. I honestly never missed the feature.

Right now we're using "github theme". It does seem that github styling in highlight js is not in sync with github, maybe we should open an issue at their side? See this file for example: https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.CLI/Stryker.CLI/CLIOptions.cs. It has literals in blue.

**Comment by richardwerkman** [comment]
Might there be a way for the mutation-testing-elements generator (like stryker-net) to include a theme? That way the `mutation-testing-elements.js` file doesn't need to include a lot of themes.

Another benefit is that each generator can choose their own theme.

**Comment by richardwerkman** [comment]
I checked this again and the literals are now blue! So the issue seems fixed (at least for Stryker.NET)
