### ISSUE TITLE
Documented Scala does not work on windows

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#332]
I've installed sbt via the msi (as instructed [by the readme](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-metrics-scala#contributing)), yet `npm test` doesn't work.

@hugo-vrijswijk  could you please help me out?

![image](https://user-images.githubusercontent.com/1828233/73819098-17c89a80-47ef-11ea-9e74-88d17fc4cee6.png)

**Comment by hugo-vrijswijk** [comment]
I changed the command for it the other day and it looks like you're on an older version. Could you try that and see if it works?

**Comment by nicojs** [comment]
Yes, fixed it. Thank you!
