### ISSUE TITLE
Show testrun result for each mutant

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/mutation-testing-elements#36]
It would be nice if we could show why a mutant was marked as killed by displaying the testrun output. That way users can see what test case killed the mutant.

This could also help by detecting false positives. When the mutation score is much higher than expected it could be seen that many mutants have the same testrun output (for example a bad unit test that fails randomly)

We could show the testrun output when clicking on the mutant.

**Comment by nicojs** [comment]
Sounds good 👍 

How would you like the schema to change? Where should the test output be added? Should it be an array? Or a single string?

**Comment by nicojs** [comment]
Maybe we can have an `"annotation"` field? That way it could be reused for example an error message (for `MutantState.RuntimeError`).

**Comment by richardwerkman** [comment]
I think that depends on how specific we want to display the output in the report. If we choose for a generic `annotation` field we can't show it as testoutput as it could contain any value.

Maybe we could add an array to the schema for `annotations`? In the array we could add a name and a value like:
```js
"annotations": [
    "name": "test run result",
    "value": "Test run for C:\Dev\ExampleProjects\FullFramework App\FullFrameworkApp.Test\bin\Debug\FullFrameworkApp.Test.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3,7820 Seconds"
]
```

That way the report generators could choose themselves what annotations to display for each mutant.
