### ISSUE TITLE
Auto loading of languages breaks mutation testing elements

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#393]
When the mutation-testing-elements report loads a language it does not have build-in syntax highlighting for, it will fall back on the autoloader. It will actually download the language highlighting on the spot. This works with the [prism autoloader plugin](https://github.com/PrismJS/prism/tree/master/plugins/autoloader).

However, there is currently no way to register a callback for when syntax highlighting is done. This is vital since we need to attach mutants to the properties of the mutant-components here: https://github.com/stryker-mutator/mutation-testing-elements/blob/20b3eabfb89e9791d7425531736a17964f35d93e/packages/mutation-testing-elements/src/components/mutation-test-report-file/index.ts#L117

The result is that the mutants will not be bound to the `mutation-test-report-mutant` elements which in turn makes the mutants invisible 
![image](https://user-images.githubusercontent.com/1828233/77828933-d386b600-711e-11ea-9be4-010d858bcd44.png)

See https://github.com/PrismJS/prism/issues/2275

Thanks to @theofidry for pointing this out to me in https://github.com/infection/infection/pull/1149

As a workaround, we should disable autoloading and just add languages whenever we want to support one. We'll be adding php shortly 🤝

**Comment by nicojs** [comment]
Fixed with the pr

**Comment by theofidry** [comment]
👍
