### ISSUE TITLE
Feature request: Survived mutant stepper

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/mutation-testing-elements#406]
It would be nice to be able to skip though a file by using some arrows.

Kinda like clicking next search result or next conflict in a merge confict editor. That way we can quickly check for survived and/or not covered mutants without scrolling trough the whole file.

Something like (excuse my bad designer skills):
![image](https://user-images.githubusercontent.com/14224500/78359164-c8b3a180-75b4-11ea-8d7f-be8c644c6865.png)

This is especially useful when there are few survived mutants present in a large file. It's like _where's waldo_ at the moment 😅

**Comment by nicojs** [comment]
> This is especially useful when there are few survived mutants present in a large file. It's like where's waldo at the moment 😅

![image](https://user-images.githubusercontent.com/1828233/78359886-2d233080-75b6-11ea-8445-6f596722191d.png)

This would be a great addition. Some questions:

* How should we show which mutant is "selected"? I assume it is just expanded?
* When click next mutant, it will go to the next file with a survived mutant if the last mutant was expanded, right?
* What do we do when all mutants are expanded en "next" is clicked (via "expand all")
* What do we do when you just viewed all mutants? Wrap around to the first one?
* Do we also want to support a "viewed" flag? Like GitHub PR's? 
![image](https://user-images.githubusercontent.com/1828233/78360242-c7837400-75b6-11ea-9d80-372a31c8a7d4.png)
* What do we do when there are no survived mutants?

**Comment by richardwerkman** [comment]
> How should we show which mutant is "selected"? I assume it is just expanded?

Expanded should be clear enough.

> When click next mutant, it will go to the next file with a survived mutant if the last mutant was expanded, right?

It would be cool if we can support file skipping. But for a first implementation I was thinking of the file as the scope.

> What do we do when all mutants are expanded en "next" is clicked (via "expand all")

I would say first all mutants are de-expanded and then the next mutant is expanded. This means we have to keep track of which mutant was last expanded by the feature?

> What do we do when you just viewed all mutants? Wrap around to the first one?

Or display a message that all mutants were found? (like: congrats that were all survived mutants) Especially if we skip though files it could be confusing if it just keeps skipping.

> Do we also want to support a "viewed" flag? Like GitHub PR's?

Do you mean per mutant or per file? I can imagine a flag per mutant could be nice, as you write a unit test for the mutant and go on to the next mutant. It would be cool if we can even store the state. If you close the report and open the next day you still see at what mutant you were.

> What do we do when there are no survived mutants?

We could not display the arrows? Show the message for the last mutant.

**Comment by Mobrockers** [comment]
> When click next mutant, it will go to the next file with a survived mutant if the last mutant was expanded, right?

I think this might get confusing, would prefer the arrow to just become greyed out to show I'm at the end of the file. Otherwise I might skip to the middle of a next file (what is the next file?) and have no clue where I am.
