### ISSUE TITLE
Html report stuck when the amount of data is too large

### ISSUE THREAD

**Issue by freemanwang** [stryker-mutator/mutation-testing-elements#423]
Hi, there. Thanks for your excellent work, my team is going well with stryker recently, and we are trying to recommand it to other teams.
We've also met some trouble with the html report feature recently. That is: when the json data is too large, the whole report page would stuck. 
For example, a js file which contains nearly 1300 mutants would stuck for about 15-20s or even more. Another file with 4800+ mutants(I know this file is unreasonably large.....) got stucked for too long that chrome suggest to close it because of no responding.
Now I try to display  the ' on-loading' tag when some big file is loading, but if too large file(like I mentioned before) is clicked, the whole page would stuck and I have to close it.
I wonder if it is possible to add some feature such as lazy loading to solve this problem?
Thanks for you time any way.

**Comment by nicojs** [comment]
Hi @freemanwang 👋 

Well, I've got to say, out of all the issues, this is one of the nicest to have. 😁

I guess the first thing we need to do is investigate what exactly the problem is. When do performance issues occur? Is it when opening the report? Or when navigating to a big file within the report?

**Comment by freemanwang** [comment]
@nicojs It occurs when navigating to a big file within the report.
Sorry I was busy last week, I forgot to check your reply.
Opening the report is always going well,  but when click a big file(such as over 1000 mutants) in the report main page( I call it Model-Page ) to see some details, it would stuck for a while. 
This also happened when one kind of mutants disapear/show if the amount is large. For example, a file contains 600 survived mutants, first I unselect the survived selector, all survived mutants will disapear, then I select the survived selector, it would take a while (around 5s) to reflow the page to show all 600+ mutants.
If the mutants amout is not too large, the reflow work is unnoticeable.So as navigating to a big file within the report.

**Comment by rouke-broersma** [comment]
We have a new report display which might or might not fix this problem. Please let us know if this is still a problem with the new report.
