### ISSUE TITLE
Navigation in HTML report and 0x60 ASCII character

### ISSUE THREAD

**Issue by alexanderkozlenko** [stryker-mutator/mutation-testing-elements#49]
Navigation in HTML report fails (blank screen) if source file name contains `0x60` ASCII character. Tested with Google Chrome 75.0 and Mozilla Firefox 67.0. Example report: [mutation-report.zip](https://github.com/stryker-mutator/mutation-testing-elements/files/3365905/mutation-report.zip)

**Comment by nicojs** [comment]
Thanks for reporting! Indeed we forget to decode the url components with `decodeURIComponent`. On it
