### ISSUE TITLE
Think about versioning in the report json

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#5]
For example: when showing the report on the dashboard, it needs to know which version to use.

**Comment by Mobrockers** [comment]
I propose that we use semver for both the schema and report components where the report components follow the major.minor versions from the schema, but do not need to have the same patch versions.

**Comment by hugo-vrijswijk** [comment]
Perhaps we should also include the version in the report schema json. So on the dashboard, the correct one can be loaded from unpkg

**Comment by Mobrockers** [comment]
Yes that is what I meant as well. The json report should have the schema version it was generated from included as a value.

**Comment by nicojs** [comment]
Cool, I like what you're saying. Luckily, unpkg adheres to semver. See https://unpkg.com/. So should just be able to reference it like `unpkg.com/mutation-testing-elements@^1.1/dist/mutation-test-elements.js`.

I would suggest keeping `mutation-test-elements.js` versioning in sync with the schema versioning.

**Comment by Mobrockers** [comment]
@nicojs the schema version is currently '1' according to the schema. This is not yet in line with the proposal to use semver.

**Comment by nicojs** [comment]
> the schema version is currently '1'

What do you mean with that exactly? The version in the `package.json` file will be automatically released using the [lernajs](https://lernajs.io/) build.

I would like to make a small adjustment:

> I would suggest keeping `mutation-test-elements.js` versioning in sync with the schema versioning.

I think we _shouldn't allow patch_ releases of the schema. It doesn't make sense, as the schema does not have an implementation. I would keep minor versions for additions to the schema and major versions for breaking changes (we should have those as little as posible). The major.minor version of the schema should always be in sync with the major.minor version of the mutation-test-report-app element. For example:

| Schema version | Supported mutation-testing-elements implementations |
| ------------- | ------------- |
| `1.0`  | `1.0.0`, `1.0.1` |
| `1.1` | `1.0.0`, `1.0.1`, `1.1.0`, `1.1.1` |
| `2.0` | `2.0.0`, `2.0.1` |

**Comment by Mobrockers** [comment]
That is what I suggested as well, so I agree :)

> I propose that we use semver for both the schema and report components where the report components follow the major.minor versions from the schema, but do not need to have the same patch versions.
