### ISSUE TITLE
Azure DevOps dark mode makes the Mutation Report text unreadable

### ISSUE THREAD

**Issue by robertlarkins** [stryker-mutator/mutation-testing-elements#531]
The generated Mutation Report uses text colors that makes the text unreadable when using Dark Mode in Azure DevOps:
![image](https://user-images.githubusercontent.com/14414215/84585689-699cc380-ae66-11ea-9829-1542cf065afa.png)
even though all the text is there (shown by selecting the text):
![image](https://user-images.githubusercontent.com/14414215/84585701-80dbb100-ae66-11ea-9535-cb075dc76aca.png)

**Comment by Mobrockers** [comment]
@robertlarkins stryker has a dark mode report now. Is it better readable?
