### ISSUE TITLE
Inconsistent HTML ~strikethrough~ formatting

### ISSUE THREAD

**Issue by cbrunnkvist** [stryker-mutator/mutation-testing-elements#537]
### Summary

I believe the original code should always be crossed-out when any of its mutants are "opened" (i.e. clicked) in the HTML reports. What seems to be happening instead is that only _the last one of them_ actually triggers the `text-decoration: line-through` over its original code.

#### Example A (only mutant "3" uses strikethrough):

<img width="409" alt="Screen Shot 2020-06-08 at 13 28 57" src="https://user-images.githubusercontent.com/34006/84000210-75801580-a98e-11ea-90ac-c0ad4e563aa2.png">
<img width="410" alt="Screen Shot 2020-06-08 at 13 29 05" src="https://user-images.githubusercontent.com/34006/84000208-74e77f00-a98e-11ea-9d96-0b2a6f24fc89.png">

#### Example B (only mutant "8" uses strikethrough):

<img width="476" alt="Screen Shot 2020-06-08 at 13 29 31" src="https://user-images.githubusercontent.com/34006/84000206-73b65200-a98e-11ea-91f3-04c4562c0d91.png">
<img width="456" alt="Screen Shot 2020-06-08 at 13 29 38" src="https://user-images.githubusercontent.com/34006/84000205-731dbb80-a98e-11ea-8221-0222fb10542b.png">
<img width="469" alt="Screen Shot 2020-06-08 at 13 29 45" src="https://user-images.githubusercontent.com/34006/84000196-6ef19e00-a98e-11ea-992b-72c5649b0427.png">

### Stryker4s config

_(not relevant / defaults)_

### Stryker4s environment

```
stryker4s 0.8.0
```

**Comment by hugo-vrijswijk** [comment]
@cbrunnkvist I've transfered your issue to the mutation-testing-elements repo as you can see. Safari falls within our supported browsers, I believe as it is a _somewhat_ modern browser

**Comment by rouke-broersma** [comment]
We have a new report which may or may not solve this problem. Please let us know if it does not.
