### ISSUE TITLE
Feature request: Add absolute path as metadata

### ISSUE THREAD

**Issue by p3pijn** [stryker-mutator/mutation-testing-elements#588]
I'd like to request to add a metadata field with the absolute path to the project folder to the schema. By doing so, automated tools that parse mutation testing reports can more easily and reliably find the actual file on disk or correlate the results with findings from other tools.

See here for an example, here the projectRoot containing an absolute path is added to the schema:
```
{
  "schemaVersion": "1.3",
  "projectRoot": "/some/location"
  "files": {
    "SomeClass.cs": {
		...
    }
  }
}
```

See here for a description of a use case: https://github.com/stryker-mutator/stryker-net/issues/1154

**Comment by nicojs** [comment]
That seems like a fair addition. 

Feel free to add it if you have the time, if not, one of us will get around to it eventually 👍

**Comment by hugo-vrijswijk** [comment]
I think this is now implemented in the schema. Not sure what the status for each project is of adding it to the schema
