### ISSUE TITLE
Publish used configuration

### ISSUE THREAD

**Issue by legopiraat** [stryker-mutator/mutation-testing-elements#6]
It would be a nice addition if we could also push the used configuration for the mutation run.

Why would we want this?

Well, when we configure for example configure the thresholds to break on 70% mutation score I expect the front end to do some nice displaying on warning statuses. When for the next test run I set the mutation score threshold to 10% all will be green I suppose. It's then hard to compare the reporting from one report to another. 

The configuration would be a nice addition to make the report more meaningful in a long history.

**Comment by nicojs** [comment]
So you are only interested in the threshold configuration? 

Personally I don't feel like the configuration (as text content or key-value pairs) should be part if the mutation report json. The threshold configuration might be something we want, but than I would maybe remove the `health` property (as it duplicates coloring configuration).

**Comment by Mobrockers** [comment]
I also don't think we should then remove the health property, as then the report will have to calculate the colour to use, it will no longer be 'dumb'.

**Comment by nicojs** [comment]
I don't think the end use configuration would be something we need to provide in the schema. The schema is extensible, so feel free to add a field like `customData` and add the configuration there.
