### ISSUE TITLE
Smallest scope mutation result should decide report highlighting

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/mutation-testing-elements#634]
Current:
![image](https://user-images.githubusercontent.com/3595932/92215132-a04a0f00-ee94-11ea-8a29-21bcf19fab1f.png)

46 is Killed but the highlighting shows the mutation as Survived because the mutation of the larger scope (empty list mutation) is Survived.

I think the smallest scope highlighting should win. I'm not sure what the rules are currently for what highlighting gets applied.

Should be:
![image](https://user-images.githubusercontent.com/3595932/92215569-47c74180-ee95-11ea-8562-0be908de61ef.png)

**Comment by nicojs** [comment]
Hmm, interesting. I was of the opinion that you would want the most "dramatic color" to "win". 

This is done here: 

https://github.com/stryker-mutator/mutation-testing-elements/blob/5f6c02f6fa18c539092cb143befc0a8c3e97ffe2/packages/mutation-testing-elements/src/lib/BackgroundColorCalculator.ts#L43-L55

My reasoning here was that you might have 2 mutants on the same line, one starting 1 char after the other. For example:

```
if ( [1]![2]a ) {
}
```

If 2 were killed here, but 1 survived, you might be fooled into thinking both are killed. 

I'm open to the suggestion though, maybe "looking at the bright side" is better.

**Comment by Mobrockers** [comment]
I don't think that's neccesarily wrong, except that the bigger scope mutant covers the smaller scope, which makes it near invisible. 46 is coloured red because it's within 45 and 45 is red.

**Comment by rouke-broersma** [comment]
I think this has been done on the new report
