### ISSUE TITLE
Dry typescript types

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#648]
Our current typescript types are crafted by hand. However, there are ways to generate the types from JSON schema using https://www.npmjs.com/package/json-schema-to-typescript

**Comment by mohammed786** [comment]
Hey @nicojs can you please explain a bit more on this issue?

**Comment by Mobrockers** [comment]
@mohammed786 We have a json schema here: https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/mutation-testing-report-schema/src/mutation-testing-report-schema.json

And we have types for that schema here: https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-report-schema/src/api

Those types are currently 'hardcoded' but they could be generated from the schema instead. That way the types are automatically up to date with the schema.

@nicojs Please add any additional details about when/how the generation would take place. For example: is this done in CI and added to the git repo by the CI?

**Comment by nicojs** [comment]
This package is work: https://github.com/bcherny/json-schema-to-typescript

Types should be the exact same.

**Comment by nicojs** [comment]
This is already done since then
