### ISSUE TITLE
Improve display of mutations

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/mutation-testing-elements#649]
The current way of showing mutants is acceptable but it could be a lot better. My main concerns are:

- A lot of mutations on the same code looks rediculous
- It's hard to spot the difference in huge/complex mutations

Example:
![image](https://user-images.githubusercontent.com/14224500/94903763-8e12bf00-049a-11eb-981c-b2711a33b915.png)

My idea is to show the mutation like github shows a change. That way we solve both problems at once.

![image](https://user-images.githubusercontent.com/14224500/94928939-b1526400-04c4-11eb-9c02-b1f59c4cd043.png)

The idea is that we still show the mutation numbers with the same colours next to the original code. But when clicked a new line (or lines) appear below the mutated code. In these lines the acutal difference is highlighed. We could calculate the difference in the js so the mutation test frameworks don't have to calculate the actual spans.

I think we would have to add that only one mutation can be viewed at a time, as adding multiple extra row lines would get confusing.

I hope this change will improve readability and look a bit more professional 🤩

**Comment by nicojs** [comment]
The current solution is not ideal, I agree. I'm open to improvements. This sounds like a good one. We would need to prototype this and see what works best.

**Comment by nicojs** [comment]
Implemented with #1515
