### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#696]
It would be very cool if we could add a dark mode switch. 

![image](https://user-images.githubusercontent.com/1828233/96963501-081ded00-1509-11eb-8978-77c91d2b3a12.png)

It would allow users to switch to "dark mode". In dark mode, the theme will be 🥁🥁🥁 Dark 🌑! 

A couple of points:
* We're currently using bootstrap. We should be able to find some guidance online as to how to make this "dark".
* It should be possible to switch on the fly, without a reload.
* I think we should store the preference of the user in local storage. Maybe allow for more user preferences to be stored later.
* It should be possible to load the report with a 'default' mode. That way, mutation testing frameworks can allow a "dark mode" configuration in their respective config file (like "stryker.conf.json"), or in azure DevOps, the azure DevOps dark mode setting can be communicated.

**Comment by dukedagmor** [comment]
I know there are a lot of plugins like: https://darkreader.org/ to generate a darkmode for sites that don't have one. I do not know if there is a way to support these plugins so they detect the darkmode. Could be something to look into.

**Comment by nicojs** [comment]
Fixed in #697

@dukedagmor thanks for the plug, I didn't know about that one yet. However, we want to be able to switch in an offline environment or behind a corporate proxy. Really, the report should stand on its own.
