### ISSUE TITLE
Test resources should use relative instead of absolute paths for file keys

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/mutation-testing-elements#712]
Example:
https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/mutation-testing-elements/testResources/csharp-example/mutation-report.json#L8

**Comment by nicojs** [comment]
I don't understand. The schema is agnostic about this right? It would be up to the mutation testing framework to choose whether or not to use absolute paths.
