### ISSUE TITLE
Allow for test framework and test framework version keys in schema

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/mutation-testing-elements#720]
In stryker.net we have a feature we call dashboard compare. You can use it to pull a past mutation report from a storage location and use that result to fill in any mutants in code that has not been changed in order to speed up test runs.

I would like to be able to reject a past mutation report if it was generated using a different version of stryker.NET (to prevent incorrect results due to changes between stryker versions), as well as reject the report if it was not created by stryker.net (to prevent unneccesary processing when we know there is no way for the report to be valid for stryker.net).

@nicojs @hugo-vrijswijk do you guys see any issues adding this information to the report?

**Comment by hugo-vrijswijk** [comment]
One thing that comes to mind is that sbt supports having multiple test frameworks for a single test project

**Comment by Mobrockers** [comment]
Sorry by used test framework I mean the mutation test framework (or tool, what do we call ourselves?) is it stryker.net, stryker4s, mull, infectionphp etc.

Since there are multiple c# mutation testing frameworks and those frameworks might decide to use the schema, there could theoretically be conflicts.

**Comment by hugo-vrijswijk** [comment]
Stryker.NET currently is the only framework that supports this dashboard compare, right? Plus if Stryker is picking up a wrong report then it has to be due to misconfiguration. It seems like you'd have to have checks anyway (what if the report is also from Stryker.NET but just from a different project?) so I'm not sure how much value this would add

**Comment by Mobrockers** [comment]
Stryker.NET is the only framework that supports dashboard compare, it is not the only framework that supports the dashboard.

Of course we'll have to check in other ways as well, but this information would be a clear indication that something is wrong, whereas other checks would be more or less guesswork. We can tell that the report doesn't work, but we cannot be sure why.

And there are at least two other c# MT frameworks being worked on at this time, thought I don't think they support the dashboard yet.

Another use case would be statistics. We would have more information about at least the kind of projects using the dashboard or dashboard compare.

**Comment by nicojs** [comment]
Maybe it makes sense to add a more general "metadata" field. We can allow this field to be key-value pairs, thus allowing data for multiple use cases. The HTML reporter would ignore this field (or have a way to show it in a table or something).

Sounds good?

**Comment by Mobrockers** [comment]
> Maybe it makes sense to add a more general "metadata" field. We can allow this field to be key-value pairs, thus allowing data for multiple use cases. The HTML reporter would ignore this field (or have a way to show it in a table or something).
> 
> Sounds good?

I think a case could be made for both kinds of metadata. I think MT test framework name and version are standardizable enough information to be first class citizens. Also things like the project name and version and module names that we now put in the dashboard only. Information like that can be extremely useful to have in the json schema. The who-why-what of a testrun is valuable information that can be used for all kinds of purposes including general debugging.

I think putting that kind of information into a schema-less metadata map is a disservice to using a schema in the first place.
