### ISSUE TITLE
Add performance statistics, tests, system and config to schema

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#786]
This issue combines other issues to create a coherent design of changes we want to make to the schema.

#720, #36 , https://github.com/stryker-mutator/stryker/issues/2647

We want to add the following information to the schema:
1. Mutation test framework configuration used for the run.
1. Tests in the test suite and how they relate to mutants (mutant coverage and "killed-by").
1. Performance statistics for the phases (setup, initial run, mutation testing), as well as performance per mutant.
1. System information of the machine that generated the report.

**Note**: We want to keep the schema _free of derived values_. Only the actual data. Derived values will still be available through the mutation-testing-metrics dependency (delivered as jar and npm package).

This example will be kept up to date with the discussion below.

```js
{
  "config": { // object - optional
    "testRunner": "jasmine" // free object format allowed here
  },
  "testFiles": { // optional
    "test/foo.spec.js": { // If the mutation testing framework cannot determine the file name, it can use an empty string as key here
        "tests": [{
          "id": "test-1"  // test ID
          "name": "foo should be bar", // required
          "location": { // location in the file, optional
            "start": {        // start position in the file, required
              "line": 4,
              "column": 6
            },
            "end": {        // end position of the test, optional
              "line": 12,
              "column": 1
            }
        }]
      }
    }
  },
  "files": {
    "test.js": {
      "mutants": [ // left out current fields for brevity 
        {
          "id": "1", 
          "static": false, // optional, marks the mutant as static/non-static
          "coveredBy": ["test-1", "test-2"], // Optional
          "killedBy": [ "test-1"], // Optional
          "testsRan": 1, // Optional, can defer from testCoverage because of "--bail" mode in test runners.
          "duration": 42 // in ms - optional
        }
      ]
    }
  },
  "performance": { // optional
    "setup": 31000, // in ms, required, fill with `0` if this run didn't contain a "setup" step
    "initialRun": 31000, // in ms, required, fill with `0` if this run didn't contain a "initialRun" step
    "mutation": 1233500 // in ms, required, fill with `0` this run didn't contain a "mutation" step
  },
  "system": {  // optional
    "ci": false, //  Required. `true` if the run was performed on a CI like Github Actions.
    "os": { // optional
      "version": "Windows 10 Pro", // optional
      "platform": "win32", // optional
      "release": "10.0.19041" // optional
    },

    "cpu": { // optional
      "model": "Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz", // optional
      "logicalCores": 16, // required
      "baseClock": 2304 // optional
    },

    // RAM can have an impact on performance when there isn't enough.
    "ram": { // optional
      "total": 34.07 // required, in MB
    }
  },
  "framework": {
    "name": "Stryker", // required
    "version": "4.2.0", // optional
    "branding": { // optional
      "homepageUrl": "https://stryker-mutator.io", // required
      "imageUrl": "https://stryker-mutator.io/images/stryker.svg" // optional, can be a data-url
    },
    "dependencies": { // optional
      "@stryker-mutator/core": "4.2.0", // key-value pair.
      "@stryker-mutator/jest-runner": "4.2.0",
      "jest": "26.6.1" ,
      "node": "14.15.1"
    }
  }
}
```

**Comment by Lakitna** [comment]
Almost everything I need can be calculated with this, nice :) It's a bit of a hassle to calculate the stuff, but if it's a generic solution it'll be worth it.

The only thing I'm missing is Stryker packages and version details. Maybe something like:

```js
{
  "stryker": {
    "version": "4.1.1",
    "plugins": [ // optional
      {
        "name": "@stryker-mutator/typescript",
        "version": "4.1.1"
      }
    ]
  }
}
```

Or

```js
{
  "versions": [
    {
      "name": "@stryker-mutator/core",
      "version": "4.1.1"
    }
  ]
}
```

Having this data is useful to separate data from Stryker versions. Enabling version comparisons. I'm not sure how this would work with a non-Javascript Stryker though.

**Comment by nicojs** [comment]
Good point. How about this?

```js
{
     "framework": {
       "name": "Stryker",
       "version": "4.2.0",
       "url": "https://stryker-mutator.io"
     },
    "environment": {
       "@stryker-mutator/core": "4.2.0", // key-value pair.
       "@stryker-mutator/jest-runner": "4.2.0",
       "jest": "26.6.1" ,
       "node": "14.15.1"
    }
}
```

I don't like "versions", because it's plural and the dashboard already adds a "version" field if you GET a report JSON, for example: https://dashboard.stryker-mutator.io/api/reports/github.com/stryker-mutator/stryker/master?module=api.

I don't like a top-level "stryker", because mutation-testing-elements is supposed to be mutation testing framework independent 🤷‍♂️.

**Comment by kmdrGroch** [comment]
I think with this data we could start doing something. Is it also possibility of adding general mutation test information? Total umber of mutants, and each type of mutations (I mean like killed/survived/timeout)

**Comment by nicojs** [comment]
@kmdrGroch that is explicitly what we don't want. As stated in the issue:

> **Note**: We want to keep the schema free of derived values.

You can get this info using [mutation-testing-metrics](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-metrics#mutation-testing-metrics) (input is a JSON object that is valid according to the schema).

**Comment by kmdrGroch** [comment]
Cool, I will just use my own scripts to get derived values :)

**Comment by Lakitna** [comment]
> Good point. How about this?

Sounds good :)

**Comment by nicojs** [comment]
Agreed, what would be a better name? I thought of `dependencies`, but that might be confusing since it would differ from the package.json's `dependencies` property. 🤷‍♂️

**Comment by Lakitna** [comment]
> Maybe we can move the dependencies property as part of the framework property? That might make sense.

Yeah, that makes more sense to me. So it would be something like this:

```js
{
    "framework": {
        "name": "Stryker",
        "version": "4.2.0",
        "url": "https://stryker-mutator.io",
        "dependencies": {
            "@stryker-mutator/core": "4.2.0", // key-value pair.
            "@stryker-mutator/jest-runner": "4.2.0",
            "jest": "26.6.1" ,
            "node": "14.15.1"
        }
    }
}
```

**Comment by nicojs** [comment]
@hugo-vrijswijk and I are implementing this in #805. We had a question about `"ram"`. @Lakitna 

What is the `"used"` here? Is it the max total ram of all the mutation testing processes combined? (test runner workers, checker workers, main processes, etc)? Or an average? Or the memory used by the main process on exit? We've currently left it out, because it is unclear to us.

**Comment by Lakitna** [comment]
I want to know if the OS has to start using the Page file because RAM is filled up. The idea behind used was to measure the RAM usage before running Stryker, so we have a clear picture of the amount of RAM available to Stryker during execution.

Maybe it should be renamed `available` or `totalAvailable`?

**Comment by hugo-vrijswijk** [comment]
> I want to know if the OS has to start using the Page file because RAM is filled up

Maybe I'm wrong, but free RAM at the start seems like a very specific use-case to me. In that case it should then be the available RAM at the start of the process? But then I can imagine people will have similarly-specific use-cases for RAM usage at the end, or the average. 

In the case of Stryker4s it is very difficult to measure on the JVM. Because you can only get the memory usage of the current JVM, not the machine it is running on. Each test-process is a separate JVM so will report its free and total RAM of that current JVM, which is completely separate of the other testrunners and JVMs, which makes the information somewhat useless.

**Comment by Lakitna** [comment]
Hmm, that does make it useless indeed. I would like to know the amount of RAM available to Stryker. This will differ when running in an imperfect environment (e.g. not in CI). On a normally used PC, you don't close every other process to run Stryker. Having a total of 32GB of RAM is useless if 30GB of it is assigned to other processes.

If I'm honest, it's not the most useful metric in the list. I can live with just the system `total`. That would allow us to (potentially) see the effects of the most notable RAM-based issues.

**Comment by nicojs** [comment]
And would that then be: 

```json
{
  "ram": 32000
}
```

Or


```json
{
  "ram": {
    "total": 32000
  }
}
```

**Comment by Lakitna** [comment]
I'd go for the second one to maximize future flexibility.

**Comment by nicojs** [comment]
I was thinking about the tests. We now have them defined as a flat structure. I'm thinking this will result in a lot of redundancy, mainly the name of the file it appears in. 

Another approach might be to add `"testFiles"` on the root of the report. This would be in line with the `"files"` we already have.

```json
{
  "testFiles": {
      "specs/foo/foo.spec.ts": {
        "spec-1": {
          "name": "foo should bar",
          "location": { "start": { "line": 4, "column": 6 } }
        }
      }
   }
}
```

The downside is that the path is that `filePath` would be required (since it is in the key). We could solve this by allowing for a file with the name `"unknown"`, or maybe `""` to signal an unknown file. Every test runner in Stryker supports reporting of the file name in tests.

We could even go crazy and merge `tests` inside `files`. A file could then either contain `mutants` or `tests`.

**Comment by hugo-vrijswijk** [comment]
I'm not sure. This seems really geared towards the JS world where there are multiple tests per file. In Scala, for example, there's 1 test per file (the class name) and no file path is known at all. Having everything fall under `unknown` is not a clean solution to me at all. Is having the same filename appear multiple times really that much of a problem? Mutant IDs also appear multiple times

**Comment by nicojs** [comment]
I'm pretty sure I was written multiple tests per file when I was writing scala code. You sure you are not confusing with test classes? Are you not able to get more fine-grained information than that?

Wouldn't it be possible to lookup the test file yourself on disk? I think in general it would be user-friendly to display the file path if you can.

Mutant IDs appear multiply times where? Test IDs do indeed, but they're just that, IDs. A file path could be repeated 40 times for 40 tests. Feels redundant to me, and it's different than how mutants are reported.

**Comment by nicojs** [comment]
It might also help us of we would ever want to show the tests themselves by allowing a `source` property on the test file object.

**Comment by hugo-vrijswijk** [comment]
Yes you can have multiple tests per file of course, but they are all usually inside a single class, and that's all we have. You can't know what tests are inside a class until you initialize the class. 

Looking up the file on disk might also be quite problematic. There's multiple locations where the file could be, and the class name does not have to correspond with the file name, they can be completely different

**Comment by nicojs** [comment]
I understand the difficulty for some languages, but leaving a place for a "test file abstraction" in the schema seems like a good idea.

How about this:

```json
{
  "testSuites": [
      {
        "filePath": "specs/foo/foo.spec.ts",
        "tests": [{
          "spec-1": {
            "name": "foo should bar",
            "location": { "start": { "line": 4, "column": 6 } }
          }
        }]
      }
   ]
}
```

A "testSuite" here doesn't have to be a file, so you can also define one suite for all tests. However, when the `filePath` is filled in, it signals that it maps 1 to 1 with that file.

**Comment by nicojs** [comment]
I had a call with @Mobrockers  and @hugo-vrijswijk  earlier today, we've aligned on a couple of changes:

* We'll use the `testFiles` idea, but make the `tests` inside them an array. This is in line with how `mutants` already work. 
* We move `url` and `imageUrl` to `branding.homepageUrl` and `branding.imageUrl` respectively
* We add a `static` boolean to mutant. This can be used to mark a mutant as static, meaning that it is executed as soon as the code is loaded, and not as part of a test run. This can be useful to report later on.

We've updated the PR (as well as the example in this issue) with these changes.

**Comment by nicojs** [comment]
Did some more small improvements (ideas from @hugo-vrijswijk ):

The folowing fields are now required:
* `system.ci`
* `system.os.platform`
* `system.cpu.logicalCores`
* `system.ram.total`

Motivation: the container object itself is optional, but if you provide it, then they should have the most prominent information at least.

**Comment by nicojs** [comment]
I've done the same for `performance`. All 3 fields are now required whenever you fill in a "performance" object. If a particular step was skipped in the mutation test run, please fill it with `0`.
