### ISSUE TITLE
Add state "ignored"

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#85]
Both Stryker.NET as Stryker have (or will have) ways to ignore certain mutations (either by mutator name or other means). We want ignored mutations to also be visible in the mutation score. We should add this as a mutator state.

See https://github.com/stryker-mutator/stryker/issues/1472 

@Mobrockers what should the name be? I would prefer `Ignored` as it is really clear that the user choose to ignore it. Something like `skipped` could have any reason.

**Comment by Mobrockers** [comment]
I like not having to change a status we already use 😁

We can provide a skipped reason already as well (skipped due to disabled mutator, skipped due to file exclusion, skipped due to method exclusion)

**Comment by hugo-vrijswijk** [comment]
I like it! Stryker4s already has the possibility to filter out mutant categories. Though working them into the report might be a bit of refactoring. 

Initially I thought 'Disabled' might make sense too, but Ignored is probably better as it doesn't imply user action (filtered out duplicate mutants could be Ignored, for example).

**Comment by nicojs** [comment]
@Mobrockers you can still use `Skipped` internally, Stryker also uses `Skipped` (if I'm not mistaken). Like I said, I think `Ignored` communicates better what the reason is for it being skipped..

**Comment by Mobrockers** [comment]
> I like it! Stryker4s already has the possibility to filter out mutant categories. Though working them into the report might be a bit of refactoring.
> 
> Initially I thought 'Disabled' might make sense too, but Ignored is probably better as it doesn't imply user action (filtered out duplicate mutants could be Ignored, for example).

I don't think duplicate mutants should be included in the report at all. When would there be a duplicate mutant? Creating a duplicate mutant should be avoided at all. It also doesn't fit with @nicojs 's reasoning for the name change, which is to clarify that the status `Ignored` always means Skipped due to user action/configuration.

**Comment by simondel** [comment]
I'd prefer to call it `Ignored`. This status is also reflected in the config for the user: https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md#ignore-methods

I'd also prefer to have a _reason_ why the mutant was ignored.

**Comment by simondel** [comment]
I'm working on adding this

**Comment by Mobrockers** [comment]
Our mutants already have a `string ResultStatusReason { get; }` so we can fill the reason if we get a field for it in the schema.
