### ISSUE TITLE
Naming the metrics for tests

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#872]
While we're implementing the details about tests I want to make sure we get the terms for those metrics just right. I also want to know exactly what we want to "count" and show to the end-user in the overview table. Here is my proposal:

(all of these are per file/directory)

* `total`:  The total number of tests.
* `pacifist`:  The total number of tests that didn't kill any mutants.
* `without coverage`: total number of tests that didn't even cover a single mutant.

@hugo-vrijswijk @Mobrockers what do you think? Am I forgetting important metrics here? What about the names?

**Comment by Mobrockers** [comment]
I think the 'pacifist' name is a bit much. It doesn't fit in with the rest of the terms we use. If we would do something like that we would need to go for it 100%.

Without coverage is confusing because it can also mean mutants without coverage.

I'm not so sure we want to show these metrics in the overview at all, since the overview is already kinda cramped with information. I think it would make it even harder to read the correct columns.

**Comment by nicojs** [comment]
> It doesn't fit in with the rest of the terms we use. 

I think it works quite well with terms like "survived" and "killed". 

I would personally love a view on my tests and I'm personally very interested in tests that didn't kill any mutants. I'm hoping to not add more clutter than we currently have. That's why I'm thinking to add it on a separate tab, that way it is really clear that you've selected an alternative view. Prototype example:

![image](https://user-images.githubusercontent.com/1828233/106610821-80b03300-6567-11eb-8549-57c8ba342c8b.png)

**Comment by Mobrockers** [comment]
It fits with survived and killed, but not with any of the other metrics. Not even with the other metrics for tests. Without coverage -> Pacifist does not match at all imo.

In my opinion Survived/Killed is already far enough as far as xmen terminology goes but I would prefer that the rest of the report is more neutral/technical. Either that or we have to change all the metrics names, which I am also not in favor of.

I do agree with putting this on a new tab, then it does not increase clutter.

I would propose the following terms:

- Not covering
- Not killing
- Killing
- Total

**Comment by nicojs** [comment]
Those sound OK. Wish there was a better name. @hugo-vrijswijk do you have ideas?

> already far enough as far as xmen terminology 

I actually got the term "pacifist" from the speedrunning world. A pacifist speedrun is a speedrun where you are not allowed to harm anyone. 💘

**Comment by Mobrockers** [comment]
> Those sound OK. Wish there was a better name. @hugo-vrijswijk do you have ideas?
> 
> > already far enough as far as xmen terminology
> 
> I actually got the term "pacifist" from the speedrunning world. A pacifist speedrun is a speedrun where you are not allowed to harm anyone. 💘

I agree that the names are not great but I think they are clear enough.

**Comment by hugo-vrijswijk** [comment]
In my opinion, `pacifist` only really makes sense if you think about it for a second. So, I'm fine with it, but I would prefer something that you can understand right away

**Comment by Mobrockers** [comment]
> In my opinion, `pacifist` only really makes sense if you think about it for a second. So, I'm fine with it, but I would prefer something that you can understand right away. I don't have a better suggestion though 🤷‍♀️

So what did you think of my suggestions
