### ISSUE TITLE
Add a "statusReason" field

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/mutation-testing-elements#891]
We currently don't have a place to put the error message for an error mutant, or the failure message for killed mutants. That is a shame because it might help the user. In Stryker, we currently put this in the description, which I think is not nice at all.

![fit](https://media.giphy.com/media/xT5LMtelPNIy6yjdTO/giphy.gif)

Proposal:

add an optional `statusReason` string field. It _should_ have:
* The error message if the mutant status is error
* The failure message if the mutant is killed.

@Mobrockers @hugo-vrijswijk thoughts?

**Comment by Mobrockers** [comment]
We don't have a mutant status of error, what is that used for? We also don't really collect the kill reason. We could buy unit test output is not gonna fit very nice in the report I don't think.

**Comment by nicojs** [comment]
So you don't mind if we add it, since you're not going to use it?

Error messages we use is the compile error in case of typescript or the runtime error in case a runtime error occurred. A runtime error can happen in javascript when the loading of the files already causes an error (without tests running). For example, mutating: `require('foo')` to `require('')`.

**Comment by Mobrockers** [comment]
Ah right of course, we do have the compile error status. Thought I don't know if it's very useful to show the compile error diagnostic in the report.

**Comment by nicojs** [comment]
Yeah, however, a failure message is. It can help people realize what their tests are doing. But adding `failureMessage` would seem rather specific. Making it a bit more generic will help us not having to introduce quite as many fields.
