### ISSUE TITLE
Incorrect schema property position

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/mutation-testing-elements#9]
https://github.com/stryker-mutator/mutation-testing-elements/blob/323f0a8c3ebdff00dc20bee6aa86e13cfe100f9d/mutation-testing-report-schema.json#L58

Perhaps I do not understand how the schema works, but I'm pretty sure this position property is a duplicate of location and should be removed

**Comment by nicojs** [comment]
There is a difference. Here is a snippet from the typescript interfaces:

```ts
export declare interface Location {
  start: Position;
  end: Position;
}

export declare interface Position {
  line: number;
  column: number;
}
```

So a position only is a single point in the file. A spans 2 positions. It's not the best naming, we're open to suggestions 😅

**Comment by Mobrockers** [comment]
I did not notice location has a reference to position: `"$ref": "#/properties/files/definitions/position"`

Fair enough

**Comment by hugo-vrijswijk** [comment]
We could call it `span`, with a start and end `position`. I also agree location and position are too similar

**Comment by richardwerkman** [comment]
For me `span` is also the more logical choice. `position` makes me think one single character is meant and not a whole array of characters.

**Comment by nicojs** [comment]
@richardwerkman 

> `position` makes me think one single character is meant and not a whole array of characters.

`Position` _is_ a single character and will remain that way. So there does not seem to be a misunderstanding there. The only question is if we should call a `start` and `end` position a `Location` or a `span`.

**Comment by richardwerkman** [comment]
@nicojs sorry I meant "`Location` makes me think one single character is meant and not a whole array of characters". The same for `position` of course. So `Location` should become a `Span` like this?

``` ts
export declare interface Span {
  start: Position;
  end: Position;
}

export declare interface Position {
  line: number;
  column: number;
}
```

**Comment by nicojs** [comment]
I would agree to changing the names of the interfaces in TS and the schema.json file. However, I would like to keep the property name what it is now. If you zoom in on a mutant, I don't see any confusion as to what is what:

```json
{
  "id" : "213",
  "mutatorName" : "StringLiteral",
  "replacement" : "s\"\"",
  "location" : {
    "start" : {
      "line" : 13,
      "column" : 25
    },
    "end" : {
      "line" : 13,
      "column" : 53
    }
  },
  "status" : "Survived"
}
```

**Comment by Mobrockers** [comment]
I'm personally fine with both Location and Position, I just had trouble finding ref tag :d

**Comment by nicojs** [comment]
I'm closing this issue, since @Mobrockers agrees 👍
